### ISSUE TITLE
NPM installation

### ISSUE THREAD

**Issue by iGitScor** [iGitScor/kickstarter#5]
The project can be installed as a npm global dependency

- Correct existing documentation
- Write documentation

**Comment by shahzeb1** [comment]
Could you please be a little more specific?
I'm down to work on this fork if I know specifically what you're looking for.

**Comment by iGitScor** [comment]
Hi @shahzeb1, thank your for having an interest in this project which is used in production

We are looking for contributors to improve the library and also to welcome other contributors.
This issue aims is to help new contributors. 

As mentioned above, the plugin has to be installed globally so we should correct `Getting started` part to specify how to do this.

_**This is an issue for a first time pull request**_

**Comment by shahzeb1** [comment]
That makes sense. So there needs to be an installation passage added to the documentation. What is the name of the NPM package?

**Comment by iGitScor** [comment]
This issue was created because developers installed them with the following command
`npm install -g https://github.com/iGitScor/kickstarter`

The problem is this does not work well with recent git version. (for example it didn't install dependencies)

We should mention the [npm package](https://www.npmjs.com/package/kickstarter-tools)
I don't know if it is better to have the install section directly available in the README.md.

**Comment by iGitScor** [comment]
Done with the integration of yarn #11
