### ISSUE TITLE
Yarn dependency management

### ISSUE THREAD

**Issue by iGitScor** [iGitScor/kickstarter#9]
Hi,

[Yarn](https://yarnpkg.com/lang/en/) is now enough mature to be used in this project.
We should add yarn in the documentation (to help developers and contributors) and generate the `yarn.lock`

Good luck

**Comment by Rhys362** [comment]
I'd like to work on this issue as a first time contribution.

Just to clarify, you need to add yarn to the project and modify the documentation to reflect this, yes?

**Comment by iGitScor** [comment]
Hi @Rhys362, I think so 😄

I usually install yarn📦  globally.
Is it good for you? If you have already use yarn, what do you prefer?
I am open to any code proposal.

Thank you

**Comment by Rhys362** [comment]
Hi @iGitScor, sorry I jumped ahead and didn't see your reply. I have added the yarn.lock file. This is my first time using yarn and so I have no preference, please instruct :smiley:

**Comment by Rhys362** [comment]
I have misunderstood, I do apologise. You just need new docs outlining how to migrate from npm and install packages globally. Sorry again for acting so stupid I'll get right on it.
